### ISSUE TITLE
Placement for x2 and x4

### ISSUE THREAD

**Issue by jnsaff** [Jan--Henrik/OtterPill#5]
Hi, the placement file seems to be for one board only and as JLC won't do placement for the single board layout only half of the x2 and quarter of the x4 boards would be populated with SMT. I am wondering whether you already have the placement files that would populate all of them? If not I'll probably try to create them myself and submit a pull request.

Or if I did something wrong with JLC a hint would be helpful.

Thank you for your awesome work!

**Comment by Jana-Marie** [comment]
Hey, I forgot to push them, sorry about that.

https://github.com/Jan--Henrik/OtterPill/tree/master/HW%20v1.2/production
