### ISSUE TITLE
LCSC part for R1,R2 on  v1.2?

### ISSUE THREAD

**Issue by geocine** [Jan--Henrik/OtterPill#8]
What is the LCSC part for this component? I checked the BOM, it was blank.

DNP | R1,R2 | Resistor_SMD:R_0402_1005Metric

**Comment by geocine** [comment]
I just read about DNP are those pads only used for testing ?

**Comment by Jana-Marie** [comment]
Hey, sorry for the late answer, they can be populated instead of FUSB302B, if no PD capabilities are needed.
